{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
{let class_content=$attribute.contentclass_attribute.content}

{switch match=$class_content.selection_type}

{* Browse. *}
{case match=0}
<div class="block">
{if $attribute.content}
<table class="list" cellspacing="0">
<tr>
    <th>{'Name'|i18n( 'ezteamroom/edit' )}</th>
    <th>{'Type'|i18n( 'ezteamroom/edit' )}</th>
    <th>{'Section'|i18n( 'ezteamroom/edit' )}</th>
</tr>
<tr>
    <td>{$attribute.content.class_identifier|class_icon( small, $attribute.content.class_name )}&nbsp;{$attribute.content.name|wash}</td>
    <td>{$attribute.content.class_name|wash}</td>
    <td>{fetch( section, object, hash( section_id, $attribute.content.section_id ) ).name|wash}</td>
</tr>
</table>
{else}
    <p>{'No relation'|i18n( 'ezteamroom/edit' )}</p>
{/if}

{if $attribute.content}
    <input class="button" type="submit" name="CustomActionButton[{$attribute.id}_remove_object]" value="{'Remove object'|i18n( 'ezteamroom/edit' )}" />
{else}
    <input class="button-disabled" type="submit" name="CustomActionButton[{$attribute.id}_remove_object]" value="{'Remove object'|i18n( 'ezteamroom/edit' )}" disabled="disabled" />
{/if}
{*    <input class="button" type="submit" name="CustomActionButton[{$attribute.id}_browse_object]" value="{'Add object'|i18n( 'ezteamroom/edit' )}"  onclick="javascript:ajaxpage( this.form, 'contentarea', 'POST', true, 'CustomActionButton[{$attribute.id}_browse_object]' ); return false;"/>*}
    <input class="button" type="submit" name="CustomActionButton[{$attribute.id}_browse_object]" value="{'Add object'|i18n( 'ezteamroom/edit' )}" />

<input type="hidden" name="{$attribute_base}_data_object_relation_id_{$attribute.id}" value="{$attribute.data_int}" />

{* <div id="contentarea" style="display:none;"></div> *}

</div>
{/case}




{* Dropdown list. *}
{case match=1}

{def $start_node_id=$class_content.default_selection_node
     $start_node=fetch( content, node, hash( node_id, $start_node_id ) )}
<div id="attribute_{$attribute.id}_selection" class="object_relation_selection">
<select style="float: left; width: 200px;" id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_data_object_relation_id_{$attribute.id}" onchange="javascript:return teamroomDisplayImage('attribute_{$attribute.id}_item_','attribute_{$attribute.id}_selection', this.value )" onKeyDown="javascript:return teamroomDisplayImage('attribute_{$attribute.id}_item_','attribute_{$attribute.id}_selection', this.value )" onMouseMove="javascript:return teamroomDisplayImage('attribute_{$attribute.id}_item_','attribute_{$attribute.id}_selection', this.value )">
{if $attribute.contentclass_attribute.is_required|not}
<option value="" {section show=eq( $attribute.data_int, '' )}selected="selected"{/section}>{'No relation'|i18n( 'ezteamroom/edit' )}</option>
{/if}
{foreach fetch( content, list, hash( parent_node_id, $start_node.node_id, sort_by, $start_node.sort_array|prepend('class_identifier', true) ) ) as $item}
    {if $item.object.content_class.identifier|eq('folder')}
        <optgroup label="{$item.name|wash()}">
        {foreach fetch( content, list, hash( parent_node_id, $item.node_id, sort_by, $item.sort_array|prepend('class_identifier', true) ) ) as $subitem}
        <option value="{$subitem.contentobject_id}" {if eq( $attribute.data_int, $subitem.contentobject_id )}selected="selected"{/if}>{$subitem.name|wash}</option>
        {/foreach}
        </optgroup>
    {else}
    <option value="{$item.contentobject_id}" {if eq( $attribute.data_int, $item.contentobject_id )}selected="selected"{/if}>{$item.name|wash}</option>
    {/if}
{/foreach}
</select>

{foreach fetch( content, list, hash( parent_node_id, $start_node.node_id, sort_by, $start_node.sort_array ) ) as $item}
    {if $item.object.content_class.identifier|eq('folder')}
        {foreach fetch( content, list, hash( parent_node_id, $item.node_id, sort_by, $item.sort_array|prepend('class_identifier', true) ) ) as $subitem}
        <div id="attribute_{$attribute.id}_item_{$subitem.contentobject_id}" style="display:none;" class="relationobject_preview">
        {node_view_gui view="edit_preview" content_node=$subitem}
        </div>
        {if eq( $attribute.data_int, $subitem.contentobject_id )}
            <script type="text/javascript"><!--
                teamroomDisplayImage('attribute_{$attribute.id}_item_','attribute_{$attribute.id}_selection', "{$subitem.contentobject_id}" )
            //--> </script>
        {/if}
        {/foreach}
    {else}
        <div id="attribute_{$attribute.id}_item_{$item.contentobject_id}" style="display:none; margin-left: 220px;" class="relationobject_preview">
        {node_view_gui view="edit_preview" content_node=$item}
        </div>
        {if eq( $attribute.data_int, $item.contentobject_id )}
            <script type="text/javascript"><!--
                teamroomDisplayImage('attribute_{$attribute.id}_item_','attribute_{$attribute.id}_selection', "{$item.contentobject_id}" )
            //--> </script>
        {/if}
    {/if}
{/foreach}

{if $class_content.fuzzy_match}
<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_fuzzy_match" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" name="{$attribute_base}_data_object_relation_fuzzy_match_{$attribute.id}" value="" />
{/if}
</div>
{/case}


{* Dropdown tree. Not implemented yet, thus unavailable from class edit mode. *}
{case match=2}
{/case}

{case/}

{/switch}

{/let}
{/default}
