{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $site_url=ezini('SiteSettings','SiteURL')}
{def $subject=concat( $site_url, ' registration approved'|i18n('ezteamroom/membership') )}
{'Thank you for registering at %siteurl.'|i18n('ezteamroom/membership', , hash( '%siteurl', $site_url ))}

{'Your registration has been approved. You can login with your account %username.'|i18n( 'ezteamroom/membership', , hash( '%username', $user.login ) )}

{'Click the following URL to login:'|i18n( 'ezteamroom/membership' )}
http://{$site_url}{'/user/login'}